Bump MSRV to 1.67
toml requires it.

```
error: package `toml v0.8.4` cannot be built because it requires rustc 1.67 or newer, while the currently active rustc version is 1.66.1
```