Fix error with custom targets
```
thread 'resolve::tests::parse_cfg_list' (3195) panicked at src/resolve.rs:724:92:
called `Result::unwrap()` on an `Err` value: Error(Other("process didn't exit successfully: `rustc --print cfg --target /home/runner/work/cargo-config2/cargo-config2/tests/fixtures/target-specs/avr-unknown-gnu-atmega2560.json` (exit status: 1)\n--- stderr\nerror: error loading target specification: custom targets are unstable and require `-Zunstable-options`\n  |\n  = help: run `rustc --print target-list` for a list of built-in targets\n\n"))
```