Bump MSRV to 1.66
toml_edit (used by toml) requires it.

```
error: package `toml_edit v0.19.15` cannot be built because it requires rustc 1.66.0 or newer, while the currently active rustc version is 1.65.0
```