tests: Address i586-pc-windows-msvc removal
```
thread 'cfg_expr::tests::eval::very_specific' panicked at src/cfg_expr/tests/eval.rs:69:75:
called `Result::unwrap()` on an `Err` value: Error(Other("process didn't exit successfully: `rustc --print cfg --target i586-pc-windows-msvc` (exit status: 1)\n--- stderr\nerror: Error loading target specification: the `i586-pc-windows-msvc` target has been removed. Use the `i686-pc-windows-msvc` target instead.\n       Windows 10 (the minimum required OS version) requires a CPU baseline of at least i686 so you can safely switch. Run `rustc --print target-list` for a list of built-in targets\n\n"))
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/1aeb99d248e1b0069110cb03c6f1dcc7b36fd7f3/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/1aeb99d248e1b0069110cb03c6f1dcc7b36fd7f3/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/1aeb99d248e1b0069110cb03c6f1dcc7b36fd7f3/library/core/src/result.rs:1704:5
   3: core::result::Result<T,E>::unwrap
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1109:23
   4: cargo_config2::cfg_expr::tests::eval::very_specific
             at ./src/cfg_expr/tests/eval.rs:69:17
   5: cargo_config2::cfg_expr::tests::eval::very_specific::{{closure}}
             at ./src/cfg_expr/tests/eval.rs:42:19
   6: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/1aeb99d248e1b0069110cb03c6f1dcc7b36fd7f3/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```