Bump MSRV to 1.76
```
  error: package `toml v0.9.7` cannot be built because it requires rustc 1.76 or newer, while the currently active rustc version is 1.71.1
  Either upgrade to rustc 1.76 or newer, or use
  cargo update -p toml@0.9.7 --precise ver
  where `ver` is the latest version of `toml` supporting rustc 1.71.1
```