Bump MSRV to 1.70
home 0.5.9 requires it

```
error: package `home v0.5.9` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.1
```